/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package havayolubilgisistemi;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AsusTuf
 */
public class YoneticiPage extends javax.swing.JFrame {

    private String adi;
    private static int id = 0;
    private String mesaj;

    public YoneticiPage(Yonetici yonet) {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException
                | IllegalAccessException e) {
            e.printStackTrace();
        }
        Color backgroundColor = new Color(150, 239, 255);
        getContentPane().setBackground(backgroundColor);
        if (Yonetici.getYonet().getId() != id) {
            Giris();
        }
        Girisbutton.setEnabled(false);
        PassTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) { // Giriş Buttonu basmak için Şifre Yazmak Kerekir
                Girisbutton.setEnabled(true);
            }
        });
        Girisbutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                id = Integer.parseInt(PassTextField.getText()); // Şifre Dorumu Değilmi
                if (id != 0) {
                    if (Yonetici.getYonet().getId() == id) {
                        en();
                    } else {
                        mesaj = "Sifre Yanlis !";
                    }
                } else {
                    Giris();
                }
            }
        });
    }

    private YoneticiPage() {
        initComponents();
    }

    private YoneticiPage(Sefer sefer) {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException
                | IllegalAccessException e) {
            e.printStackTrace();
        }
        Color backgroundColor = new Color(150, 239, 255);
        getContentPane().setBackground(backgroundColor);
        if (Yonetici.getYonet().getId() != id) {
            Giris();
        }
        Girisbutton.setEnabled(false);
        PassTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Girisbutton.setEnabled(true);
            }
        });
        Girisbutton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                id = Integer.parseInt(PassTextField.getText());
                if (id != 0) {

                    if (Yonetici.getYonet().getId() == id) {
                        en();
                    } else {
                        mesaj = "Sifre Yanlis !";
                    }
                } else {
                    Giris();
                }
            }
        });

    }

    private void en() {
        SirketButton.setEnabled(true);
        PersonellerBtn.setEnabled(true);
        SirketButton.setEnabled(true);
        SirketlerBtn.setEnabled(true);
        PilotButton.setEnabled(true);
        HosteseButton.setEnabled(true);
        SeferBtn.setEnabled(true);
        SeferButton.setEnabled(true);
        UcakButton.setEnabled(true);
        UcusButton.setEnabled(true);
        UcuslarBtn.setEnabled(true);
        YolcuBtn.setEnabled(true);
        UcakBtn1.setEnabled(true);
        Userbutton.setEnabled(true);
        PassTextField.setText("");
        System.out.println("Welcome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeriBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PilotButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SirketButton = new javax.swing.JButton();
        HosteseButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        AdiTxt = new javax.swing.JTextField();
        adiGitBtn = new javax.swing.JButton();
        label3 = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        UcakButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NeredenCBox = new javax.swing.JComboBox<>();
        NereyeCBox = new javax.swing.JComboBox<>();
        KmTxt = new javax.swing.JTextField();
        TarihTxt = new javax.swing.JTextField();
        SureTxt = new javax.swing.JTextField();
        Nlabel4 = new java.awt.Label();
        Nlabel7 = new java.awt.Label();
        label6KM = new java.awt.Label();
        label8S = new java.awt.Label();
        label9T = new java.awt.Label();
        SeferGitBtn = new javax.swing.JButton();
        SeferButton = new javax.swing.JButton();
        SaatTxt = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        UcretTxt = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        label5 = new java.awt.Label();
        UcakBox = new javax.swing.JComboBox<>();
        UcusGitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SeferCBox = new javax.swing.JComboBox<>();
        UcusButton = new javax.swing.JButton();
        SaatBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        PersonellerBtn = new javax.swing.JButton();
        SirketlerBtn = new javax.swing.JButton();
        YolcuBtn = new javax.swing.JButton();
        SeferBtn = new javax.swing.JButton();
        UcakBtn1 = new javax.swing.JButton();
        UcuslarBtn = new javax.swing.JButton();
        Userbutton = new java.awt.Button();
        PassTextField = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        Girisbutton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        GeriBtn.setBackground(new java.awt.Color(95, 189, 255));
        GeriBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GeriBtn.setForeground(new java.awt.Color(123, 102, 255));
        GeriBtn.setText("Geri");
        GeriBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        GeriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(95, 189, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        PilotButton.setBackground(new java.awt.Color(150, 239, 255));
        PilotButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PilotButton.setForeground(new java.awt.Color(123, 102, 255));
        PilotButton.setText("Pilot");
        PilotButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PilotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilotButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("    Ekle");

        SirketButton.setBackground(new java.awt.Color(150, 239, 255));
        SirketButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SirketButton.setForeground(new java.awt.Color(123, 102, 255));
        SirketButton.setText("Şirket");
        SirketButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SirketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SirketButtonActionPerformed(evt);
            }
        });

        HosteseButton.setBackground(new java.awt.Color(150, 239, 255));
        HosteseButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        HosteseButton.setForeground(new java.awt.Color(123, 102, 255));
        HosteseButton.setText("Hostese");
        HosteseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        HosteseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HosteseButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(150, 239, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        AdiTxt.setText(" ");
        AdiTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        AdiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdiTxtActionPerformed(evt);
            }
        });

        adiGitBtn.setBackground(new java.awt.Color(150, 239, 255));
        adiGitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adiGitBtn.setForeground(new java.awt.Color(123, 102, 255));
        adiGitBtn.setText("Kaydet");
        adiGitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        adiGitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiGitBtnActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        label3.setText("Adi");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 87, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AdiTxt)
                                        .addComponent(adiGitBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AdiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adiGitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel6.setBackground(new java.awt.Color(150, 239, 255));

        UcakButton.setBackground(new java.awt.Color(150, 239, 255));
        UcakButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UcakButton.setForeground(new java.awt.Color(123, 102, 255));
        UcakButton.setText("Uçak");
        UcakButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcakButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UcakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addComponent(UcakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PilotButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(HosteseButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SirketButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13,
                                                        Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(PilotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(HosteseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(SirketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel3.setBackground(new java.awt.Color(95, 189, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel2.setBackground(new java.awt.Color(150, 239, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        NeredenCBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        NeredenCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeredenCBoxActionPerformed(evt);
            }
        });

        NereyeCBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        NereyeCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NereyeCBoxActionPerformed(evt);
            }
        });

        KmTxt.setText(" ");
        KmTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TarihTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        TarihTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarihTxtActionPerformed(evt);
            }
        });

        SureTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SureTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SureTxtActionPerformed(evt);
            }
        });

        Nlabel4.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Nlabel4.setText("Nereden");

        Nlabel7.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Nlabel7.setText("Nereye");

        label6KM.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        label6KM.setText("KM");

        label8S.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        label8S.setText("Süre");

        label9T.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        label9T.setText("Tarih");

        SeferGitBtn.setBackground(new java.awt.Color(150, 239, 255));
        SeferGitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SeferGitBtn.setForeground(new java.awt.Color(123, 102, 255));
        SeferGitBtn.setText("Kaydet");
        SeferGitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SeferGitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeferGitBtnActionPerformed(evt);
            }
        });

        SeferButton.setBackground(new java.awt.Color(150, 239, 255));
        SeferButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SeferButton.setForeground(new java.awt.Color(123, 102, 255));
        SeferButton.setText("Sefer Ekle");
        SeferButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SeferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Nlabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Nlabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(14, 14, 14)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(label9T,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(label8S,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(63, 63, 63)
                                                                .addComponent(label6KM,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(65, 65, 65)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(KmTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(NereyeCBox,
                                                                javax.swing.GroupLayout.Alignment.LEADING, 0, 205,
                                                                Short.MAX_VALUE)
                                                        .addComponent(NeredenCBox,
                                                                javax.swing.GroupLayout.Alignment.LEADING, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TarihTxt,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(SureTxt,
                                                                javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(SeferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SeferGitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(SeferGitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(SeferButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(2, 2, 2)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Nlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Nlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(NeredenCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(NereyeCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(KmTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label6KM, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TarihTxt, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label9T, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label8S, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        SaatTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        label10.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label10.setText("Saat");

        UcretTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcretTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcretTxtActionPerformed(evt);
            }
        });

        label11.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label11.setText("Ücret");

        label5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        label5.setText("Uçak");

        UcakBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcakBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcakBoxActionPerformed(evt);
            }
        });

        UcusGitBtn.setBackground(new java.awt.Color(150, 239, 255));
        UcusGitBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UcusGitBtn.setForeground(new java.awt.Color(123, 102, 255));
        UcusGitBtn.setText("Kaydet");
        UcusGitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcusGitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcusGitBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Sefer ");

        SeferCBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SeferCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeferCBoxActionPerformed(evt);
            }
        });

        UcusButton.setBackground(new java.awt.Color(150, 239, 255));
        UcusButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        UcusButton.setForeground(new java.awt.Color(123, 102, 255));
        UcusButton.setText("Uçuş Ekle");
        UcusButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(UcretTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                178, Short.MAX_VALUE)
                                                        .addComponent(UcakBox, 0, 178, Short.MAX_VALUE)
                                                        .addComponent(SaatTxt, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                178, Short.MAX_VALUE)
                                                        .addComponent(UcusButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 164,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SaatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))
                                                .addGap(79, 79, 79))
                                        .addComponent(UcusGitBtn, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(SeferCBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(UcusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(SaatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SaatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UcretTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UcakBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(UcusGitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(SeferCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel4.setBackground(new java.awt.Color(95, 189, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        PersonellerBtn.setBackground(new java.awt.Color(150, 239, 255));
        PersonellerBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PersonellerBtn.setForeground(new java.awt.Color(123, 102, 255));
        PersonellerBtn.setText("Personeller");
        PersonellerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PersonellerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonellerBtnActionPerformed(evt);
            }
        });

        SirketlerBtn.setBackground(new java.awt.Color(150, 239, 255));
        SirketlerBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SirketlerBtn.setForeground(new java.awt.Color(123, 102, 255));
        SirketlerBtn.setText("Şirketler");
        SirketlerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SirketlerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SirketlerBtnActionPerformed(evt);
            }
        });

        YolcuBtn.setBackground(new java.awt.Color(150, 239, 255));
        YolcuBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        YolcuBtn.setForeground(new java.awt.Color(123, 102, 255));
        YolcuBtn.setText("Yolcular");
        YolcuBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        YolcuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YolcuBtnActionPerformed(evt);
            }
        });

        SeferBtn.setBackground(new java.awt.Color(150, 239, 255));
        SeferBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SeferBtn.setForeground(new java.awt.Color(123, 102, 255));
        SeferBtn.setText("Seferler");
        SeferBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SeferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeferBtnActionPerformed(evt);
            }
        });

        UcakBtn1.setBackground(new java.awt.Color(150, 239, 255));
        UcakBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UcakBtn1.setForeground(new java.awt.Color(123, 102, 255));
        UcakBtn1.setText("Ucaklar");
        UcakBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcakBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcakBtn1ActionPerformed(evt);
            }
        });

        UcuslarBtn.setBackground(new java.awt.Color(150, 239, 255));
        UcuslarBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UcuslarBtn.setForeground(new java.awt.Color(123, 102, 255));
        UcuslarBtn.setText("Uçuşlar");
        UcuslarBtn.setActionCommand("Üclar");
        UcuslarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        UcuslarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UcuslarBtnActionPerformed(evt);
            }
        });

        Userbutton.setBackground(new java.awt.Color(255, 255, 255));
        Userbutton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Userbutton.setForeground(new java.awt.Color(123, 102, 255));
        Userbutton.setLabel("Personel Duzelt");
        Userbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Userbutton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SeferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE)
                                        .addComponent(UcakBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE)
                                        .addComponent(YolcuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE)
                                        .addComponent(UcuslarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE)
                                        .addComponent(PersonellerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE)
                                        .addComponent(SirketlerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 171,
                                                Short.MAX_VALUE))
                                .addGap(22, 22, 22)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(UcuslarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SirketlerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PersonellerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Userbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(YolcuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(UcakBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SeferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        PassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTextFieldActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Şifrenizi Giriniz");

        Girisbutton.setBackground(new java.awt.Color(95, 189, 255));
        Girisbutton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Girisbutton.setLabel("Giriş");
        Girisbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(57, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(GeriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25)
                                                .addComponent(PassTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)
                                                .addComponent(Girisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(67, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(GeriBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45,
                                                        Short.MAX_VALUE)
                                                .addComponent(PassTextField)
                                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 48,
                                                        Short.MAX_VALUE))
                                        .addComponent(Girisbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(63, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NereyeCBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NereyeCBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NereyeCBoxActionPerformed

    private void UcretTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UcretTxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_UcretTxtActionPerformed

    private void SureTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SureTxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SureTxtActionPerformed

    private void GeriBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GeriBtnActionPerformed
        Baslangis basla = new Baslangis();
        basla.setVisible(true);
        setVisible(false);
    }// GEN-LAST:event_GeriBtnActionPerformed

    private void UcakButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Gizle();
        UcakPage home = new UcakPage();
        home.setVisible(true);
    }

    private void SirketButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Gizle();
        label3.setEnabled(true);
        AdiTxt.setEnabled(true);
        adiGitBtn.setEnabled(true);
        adiGitBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String adi1 = AdiTxt.getText();
                if (!adi1.equals("") && !adi1.isEmpty()) {
                    new Sirket(AdiTxt.getText().trim(), null);
                    adi = "Sirket";
                    AdiTxt.setText("");
                }
            }
        });
    }

    private void SeferButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SeferButtonActionPerformed
        Gizle();
        NeredenCBox.setEnabled(true);
        NereyeCBox.setEnabled(true);
        SureTxt.setEnabled(true);
        TarihTxt.setEnabled(true);
        KmTxt.setEnabled(true);
        Nlabel4.setEnabled(true);
        Nlabel7.setEnabled(true);
        label6KM.setEnabled(true);
        label9T.setEnabled(true);
        label8S.setEnabled(true);
        SeferGitBtn.setEnabled(true);
        SaatBox.setEnabled(true);

        for (String air : HavaYolu.Airports) {
            NereyeCBox.addItem(air);
            NeredenCBox.addItem(air);
        }
        SaatBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                SureTxt.setText(SaatBox.getSelectedItem().toString());
            }
        });

    }// GEN-LAST:event_SeferButtonActionPerformed

    private void UcusButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Gizle();
        SaatBox.setEnabled(true);
        NeredenCBox.setEnabled(true);
        NereyeCBox.setEnabled(true);
        SureTxt.setEnabled(true);
        TarihTxt.setEnabled(true);
        KmTxt.setEnabled(true);
        Nlabel4.setEnabled(true);
        Nlabel7.setEnabled(true);
        label6KM.setEnabled(true);
        label9T.setEnabled(true);
        label8S.setEnabled(true);
        SaatTxt.setEnabled(true);
        UcretTxt.setEnabled(true);
        label11.setEnabled(true);
        label10.setEnabled(true);
        label5.setEnabled(true);
        SeferCBox.setEnabled(true);
        UcusGitBtn.setEnabled(true);
        UcakBox.setEnabled(true);
    }

    private void HosteseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Gizle();
        label3.setEnabled(true);
        AdiTxt.setEnabled(true);
        adiGitBtn.setEnabled(true);
        adiGitBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String adi1 = AdiTxt.getText();
                if (!adi1.equals("") && !adi1.isEmpty()) {
                    new Hostese(AdiTxt.getText().trim());
                    adi = "Personel";
                    AdiTxt.setText("");
                }
            }
        });
    }

    private void PilotButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Gizle(); // Pilot Ekle
        label3.setEnabled(true);
        AdiTxt.setEnabled(true);
        adiGitBtn.setEnabled(true);
        adiGitBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String adi1 = AdiTxt.getText();
                if (!adi1.equals("") && !adi1.isEmpty()) {
                    new Pilot(AdiTxt.getText().trim());
                    AdiTxt.setText("");
                    adi = "Personel";
                } else {
                    adi = "Personel";
                    new Personel(adi);
                }
            }
        });
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        Gizle();
        for (String air : HavaYolu.Airports) {
            NereyeCBox.addItem(air);
            NeredenCBox.addItem(air);

        }
        for (Sefer sefer : HavaYolu.UcusList) {
            String txt = sefer.nerden + "    >     " + sefer.nereye;
            SeferCBox.addItem(txt);
        }
        for (Ucak ucak : HavaYolu.UcakList) {
            String txt = ucak.name;
            UcakBox.addItem(txt);
        }
        String[] timeArray = new String[48]; // Assuming 30-minute intervals cover 48 slots in a day
        LocalTime currentTime = LocalTime.of(0, 0);

        for (int i = 0; i < timeArray.length; i++) {
            timeArray[i] = currentTime.format(DateTimeFormatter.ofPattern("HH:mm"));
            currentTime = currentTime.plusMinutes(30);
            SaatBox.addItem(currentTime.toString());
        }

        SaatBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                SaatTxt.setText(SaatBox.getSelectedItem().toString());
            }
        });

    }

    private void adiGitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (adi.equals("Personel")) {
            Ucuslar home = new Ucuslar(adi);
            home.setVisible(true);
            setVisible(false);
        } else if (adi.equals("Sirket")) {
            System.out.println(AdiTxt.getText());
            Ucuslar home = new Ucuslar(adi);
            home.setVisible(true);
            setVisible(false);
        } else {
            adi = "Personel";
            new Personel(adi);
        }
    }

    private void UcakBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UcakBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_UcakBoxActionPerformed

    private void UcusGitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        LocalTime saat = LocalTime.parse(SaatTxt.getText());
        Sefer sefer = HavaYolu.SeferList.get(SeferCBox.getSelectedIndex());
        Ucak ucak = HavaYolu.UcakList.get(UcakBox.getSelectedIndex());
        double koltuk = Double.parseDouble(UcretTxt.getText());
        new Ucus(saat, sefer, ucak, koltuk);
        Ucuslar ucus = new Ucuslar("Ucus");
        ucus.setVisible(true);
        setVisible(false);
    }

    private void SeferGitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Sefer sef = new Sefer(Float.parseFloat(KmTxt.getText()), NeredenCBox.getSelectedItem().toString(),
        NereyeCBox.getSelectedItem().toString(), SureTxt.getText(), TarihTxt.getText());
        HavaYolu.SeferList.add(sef);
        Ucuslar ucus = new Ucuslar("Sefer");
        ucus.setVisible(true);
        setVisible(false);
    }

    private void NeredenCBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NeredenCBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NeredenCBoxActionPerformed

    private void SeferCBoxActionPerformed(java.awt.event.ActionEvent evt) {
        SeferCBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = SeferCBox.getSelectedIndex();
                System.out.println("Selected Index: " + selectedIndex);

                if (!HavaYolu.SeferList.isEmpty() && selectedIndex >= 0 && selectedIndex < HavaYolu.SeferList.size()) {
                    Sefer sefer = HavaYolu.SeferList.get(selectedIndex);
                    NeredenCBox.setSelectedItem(sefer.nerden);
                    NereyeCBox.setSelectedItem(sefer.nereye);
                    NeredenCBox.setActionCommand(sefer.nerden);
                    NereyeCBox.setActionCommand(sefer.nereye);
                    SureTxt.setText(sefer.sure.toString());
                    TarihTxt.setText(sefer.formattedDate);
                    KmTxt.setText(Double.toString(sefer.KM));
                } else {
                    System.out.println("Invalid selection or SeferList is empty.");
                }
            }
        });
    }
    private void PersonellerBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Personel");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void SirketlerBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Sirket");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void YolcuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Yolcu");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void SeferBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Sefer");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void UcakBtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Ucak");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void UcuslarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("Ucus");
        ucus.setVisible(true);
        setVisible(false);
    }
    private void UserbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        Ucuslar ucus = new Ucuslar("User");
        ucus.setVisible(true);
        setVisible(false);
    }

    private void AdiTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AdiTxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_AdiTxtActionPerformed

    private void PassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PassTextFieldActionPerformed

    }// GEN-LAST:event_PassTextFieldActionPerformed

    private void GirisbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GirisbuttonActionPerformed

    }// GEN-LAST:event_GirisbuttonActionPerformed

    private void TarihTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TarihTxtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TarihTxtActionPerformed

    public void Giris() {
        SirketButton.setEnabled(false);
        PersonellerBtn.setEnabled(false);
        SirketButton.setEnabled(false);
        SirketlerBtn.setEnabled(false);
        PilotButton.setEnabled(false);
        HosteseButton.setEnabled(false);
        SeferBtn.setEnabled(false);
        SeferButton.setEnabled(false);
        UcakButton.setEnabled(false);
        UcusButton.setEnabled(false);
        UcuslarBtn.setEnabled(false);
        YolcuBtn.setEnabled(false);
        UcakBtn1.setEnabled(false);
        Userbutton.setEnabled(false);
    }

    public void Gizle() {
        SaatBox.setEnabled(false);
        UcretTxt.setEnabled(false);
        AdiTxt.setEnabled(false);
        KmTxt.setEnabled(false);
        NeredenCBox.setEnabled(false);
        NereyeCBox.setEnabled(false);
        SaatTxt.setEnabled(false);
        SureTxt.setEnabled(false);
        TarihTxt.setEnabled(false);
        SeferCBox.setEnabled(false);
        UcakBox.setEnabled(false);
        label3.setEnabled(false);
        Nlabel4.setEnabled(false);
        label5.setEnabled(false);
        label6KM.setEnabled(false);
        Nlabel7.setEnabled(false);
        label8S.setEnabled(false);
        label9T.setEnabled(false);
        label10.setEnabled(false);
        label11.setEnabled(false);
        SeferGitBtn.setEnabled(false);
        UcusGitBtn.setEnabled(false);
        adiGitBtn.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiPage.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new YoneticiPage().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdiTxt;
    private javax.swing.JButton GeriBtn;
    private java.awt.Button Girisbutton;
    private javax.swing.JButton HosteseButton;
    private javax.swing.JTextField KmTxt;
    private javax.swing.JComboBox<String> NeredenCBox;
    private javax.swing.JComboBox<String> NereyeCBox;
    private java.awt.Label Nlabel4;
    private java.awt.Label Nlabel7;
    private javax.swing.JTextField PassTextField;
    private javax.swing.JButton PersonellerBtn;
    private javax.swing.JButton PilotButton;
    private javax.swing.JComboBox<String> SaatBox;
    private javax.swing.JTextField SaatTxt;
    private javax.swing.JButton SeferBtn;
    private javax.swing.JButton SeferButton;
    private javax.swing.JComboBox<String> SeferCBox;
    private javax.swing.JButton SeferGitBtn;
    private javax.swing.JButton SirketButton;
    private javax.swing.JButton SirketlerBtn;
    private javax.swing.JTextField SureTxt;
    private javax.swing.JTextField TarihTxt;
    private javax.swing.JComboBox<String> UcakBox;
    private javax.swing.JButton UcakBtn1;
    private javax.swing.JButton UcakButton;
    private javax.swing.JTextField UcretTxt;
    private javax.swing.JButton UcusButton;
    private javax.swing.JButton UcusGitBtn;
    private javax.swing.JButton UcuslarBtn;
    private java.awt.Button Userbutton;
    private javax.swing.JButton YolcuBtn;
    private javax.swing.JButton adiGitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6KM;
    private java.awt.Label label8S;
    private java.awt.Label label9T;
    // End of variables declaration//GEN-END:variables
}
